# Machine Learning Homework - Exoplanet Exploration

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier

### Read the CSV File

In [2]:
# Read the csv file into a pandas DataFrame
cumulative = pd.read_csv('Resources/cumulative.csv')
cumulative.head()

rowid     kepid kepoi_name   kepler_name koi_disposition koi_pdisposition  \
0      1  10797460  K00752.01  Kepler-227 b       CONFIRMED        CANDIDATE   
1      2  10797460  K00752.02  Kepler-227 c       CONFIRMED        CANDIDATE   
2      3  10811496  K00753.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
3      4  10848459  K00754.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
4      5  10854555  K00755.01  Kepler-664 b       CONFIRMED        CANDIDATE   

   koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  ...  \
0      1.000              0              0              0  ...   
1      0.969              0              0              0  ...   
2      0.000              0              1              0  ...   
3      0.000              0              1              0  ...   
4      1.000              0              0              0  ...   

   koi_steff_err2  koi_slogg  koi_slogg_err1  koi_slogg_err2  koi_srad  \
0           -81.0      4.467           0.064          -0.096     0.927   
1           -81.0      4.467           0.064          -0.096     0.927   
2          -176.0      4.544           0.044          -0.176     0.868   
3          -174.0      4.564           0.053          -0.168     0.791   
4          -211.0      4.438           0.070          -0.210     1.046   

   koi_srad_err1  koi_srad_err2         ra        dec  koi_kepmag  
0          0.105         -0.061  291.93423  48.141651      15.347  
1          0.105         -0.061  291.93423  48.141651      15.347  
2          0.233         -0.078  297.00482  48.134129      15.436  
3          0.201         -0.067  285.53461  48.285210      15.597  
4          0.334         -0.133  288.75488  48.226200      15.509  

[5 rows x 50 columns]

### Explore the file

In [3]:
cumulative.shape

(9564, 50)

In [4]:
cumulative.describe()

rowid         kepid    koi_score  koi_fpflag_nt  koi_fpflag_ss  \
count  9564.000000  9.564000e+03  8054.000000    9564.000000    9564.000000   
mean   4782.500000  7.690628e+06     0.480829       0.188206       0.231598   
std    2761.033321  2.653459e+06     0.476928       0.390897       0.421875   
min       1.000000  7.574500e+05     0.000000       0.000000       0.000000   
25%    2391.750000  5.556034e+06     0.000000       0.000000       0.000000   
50%    4782.500000  7.906892e+06     0.334000       0.000000       0.000000   
75%    7173.250000  9.873066e+06     0.998000       0.000000       0.000000   
max    9564.000000  1.293514e+07     1.000000       1.000000       1.000000   

       koi_fpflag_co  koi_fpflag_ec     koi_period  koi_period_err1  \
count    9564.000000    9564.000000    9564.000000      9110.000000   
mean        0.194898       0.120033      75.671358         0.002148   
std         0.396143       0.325018    1334.744046         0.008236   
min         0.000000       0.000000       0.241843         0.000000   
25%         0.000000       0.000000       2.733684         0.000005   
50%         0.000000       0.000000       9.752831         0.000035   
75%         0.000000       0.000000      40.715178         0.000276   
max         1.000000       1.000000  129995.778400         0.172500   

       koi_period_err2  ...  koi_steff_err2    koi_slogg  koi_slogg_err1  \
count      9110.000000  ...     9081.000000  9201.000000     9096.000000   
mean         -0.002148  ...     -162.265059     4.310157        0.120738   
std           0.008236  ...       72.746348     0.432606        0.132837   
min          -0.172500  ...    -1762.000000     0.047000        0.000000   
25%          -0.000276  ...     -198.000000     4.218000        0.042000   
50%          -0.000035  ...     -160.000000     4.438000        0.070000   
75%          -0.000005  ...     -114.000000     4.543000        0.149000   
max           0.000000  ...        0.000000     5.364000        1.472000   

       koi_slogg_err2     koi_srad  koi_srad_err1  koi_srad_err2           ra  \
count     9096.000000  9201.000000    9096.000000    9096.000000  9564.000000   
mean        -0.143161     1.728712       0.362292      -0.394806   292.060163   
std          0.085477     6.127185       0.930870       2.168213     4.766657   
min         -1.207000     0.109000       0.000000    -116.137000   279.852720   
25%         -0.196000     0.829000       0.129000      -0.250000   288.660770   
50%         -0.128000     1.000000       0.251000      -0.111000   292.261125   
75%         -0.088000     1.345000       0.364000      -0.069000   295.859160   
max          0.000000   229.908000      33.091000       0.000000   301.720760   

               dec   koi_kepmag  
count  9564.000000  9563.000000  
mean     43.810433    14.264606  
std       3.601243     1.385448  
min      36.577381     6.966000  
25%      40.777173    13.440000  
50%      43.677504    14.520000  
75%      46.714611    15.322000  
max      52.336010    20.003000  

[8 rows x 45 columns]

In [5]:
cumulative.columns

Index(['rowid', 'kepid', 'kepoi_name', 'kepler_name', 'koi_disposition',
       'koi_pdisposition', 'koi_score', 'koi_fpflag_nt', 'koi_fpflag_ss',
       'koi_fpflag_co', 'koi_fpflag_ec', 'koi_period', 'koi_period_err1',
       'koi_period_err2', 'koi_time0bk', 'koi_time0bk_err1',
       'koi_time0bk_err2', 'koi_impact', 'koi_impact_err1', 'koi_impact_err2',
       'koi_duration', 'koi_duration_err1', 'koi_duration_err2', 'koi_depth',
       'koi_depth_err1', 'koi_depth_err2', 'koi_prad', 'koi_prad_err1',
       'koi_prad_err2', 'koi_teq', 'koi_teq_err1', 'koi_teq_err2', 'koi_insol',
       'koi_insol_err1', 'koi_insol_err2', 'koi_model_snr', 'koi_tce_plnt_num',
       'koi_tce_delivname', 'koi_steff', 'koi_steff_err1', 'koi_steff_err2',
       'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2', 'koi_srad',
       'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec', 'koi_kepmag'],
      dtype='object')

In [6]:
cumulative["koi_disposition"].unique()

array(['CONFIRMED', 'FALSE POSITIVE', 'CANDIDATE'], dtype=object)

In [7]:
cumulative["koi_pdisposition"].unique()

array(['CANDIDATE', 'FALSE POSITIVE'], dtype=object)

In [8]:
cumulative["kepid"].unique()

array([10797460, 10811496, 10848459, ..., 10128825, 10147276, 10156110],
      dtype=int64)

In [9]:
cumulative["koi_period"].unique()

array([ 9.48803557, 54.4183827 , 19.89913995, ...,  1.73984941,
        0.68140161,  4.85603482])

In [10]:
cumulative["koi_depth"].isnull().sum()

363

In [11]:
cumulative["koi_srad"].isnull().sum()

363

In [12]:
cumulative["koi_steff"].isnull().sum()

363

In [13]:
cumulative["kepler_name"].isnull().sum()

7270

In [14]:
cumulative["kepoi_name"].value_counts()

K03770.01    1
K01230.01    1
K00733.01    1
K07139.01    1
K01273.01    1
            ..
K04404.01    1
K03401.02    1
K02738.01    1
K00191.02    1
K01205.01    1
Name: kepoi_name, Length: 9564, dtype: int64

### After Exploring the CSV and reading the documentation

* The kepler_name have some values as NaN, so the better id/name for each planet is kepoi_name column
* koi_period - Orbital Period (days)- The interval between consecutive planetary transits
* koi_depth - Transit Depth (parts per million) - The fraction of stellar flux lost at the minimum of the planetary transit
* koi_srad - Stellar Radius (solar radii) - The photospheric radius of the star
* koi_steff - Stellar Effective Temperature (Kelvin) - The photospheric temperature of the star

https://exoplanetarchive.ipac.caltech.edu/docs/API_kepcandidate_columns.html

In [15]:
# Create a new DF with only some important columns
exoplanets_df = cumulative[["kepid",
                            "kepoi_name",
                            "kepler_name",
                            "koi_disposition",
                            "koi_pdisposition",
                            "koi_score",
                            "koi_period",
                            "koi_depth",
                            "koi_srad",
                            "koi_steff"]]
exoplanets_df.shape

(9564, 10)

In [16]:
exoplanets_df.head()

kepid kepoi_name   kepler_name koi_disposition koi_pdisposition  \
0  10797460  K00752.01  Kepler-227 b       CONFIRMED        CANDIDATE   
1  10797460  K00752.02  Kepler-227 c       CONFIRMED        CANDIDATE   
2  10811496  K00753.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
3  10848459  K00754.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
4  10854555  K00755.01  Kepler-664 b       CONFIRMED        CANDIDATE   

   koi_score  koi_period  koi_depth  koi_srad  koi_steff  
0      1.000    9.488036      615.8     0.927     5455.0  
1      0.969   54.418383      874.8     0.927     5455.0  
2      0.000   19.899140    10829.0     0.868     5853.0  
3      0.000    1.736952     8079.2     0.791     5805.0  
4      1.000    2.525592      603.3     1.046     6031.0

In [17]:
# Drop rows with NaN value from the specific columns
exoplanets_df = exoplanets_df.dropna(subset=["koi_depth","koi_srad","koi_steff","koi_score"])
exoplanets_df.shape

(7995, 10)

### Random Forest algorithm to predict koi_pdisposition
#### First we try with koi_pdisposition vs [ "koi_period" , "koi_depth", "koi_srad", "koi_steff"]

In [18]:
# Set random seed
np.random.seed(45)
# create a new column to separate train (75%) data from test (25%) data
exoplanets_df["is_train"] = np.random.uniform(0,1,len(exoplanets_df)) <= .75
exoplanets_df.head()

kepid kepoi_name   kepler_name koi_disposition koi_pdisposition  \
0  10797460  K00752.01  Kepler-227 b       CONFIRMED        CANDIDATE   
1  10797460  K00752.02  Kepler-227 c       CONFIRMED        CANDIDATE   
2  10811496  K00753.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
3  10848459  K00754.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
4  10854555  K00755.01  Kepler-664 b       CONFIRMED        CANDIDATE   

   koi_score  koi_period  koi_depth  koi_srad  koi_steff  is_train  
0      1.000    9.488036      615.8     0.927     5455.0     False  
1      0.969   54.418383      874.8     0.927     5455.0      True  
2      0.000   19.899140    10829.0     0.868     5853.0      True  
3      0.000    1.736952     8079.2     0.791     5805.0      True  
4      1.000    2.525592      603.3     1.046     6031.0      True

In [81]:
# Reordering dataframe
cols = list(exoplanets_df.columns.values) #Make a list of all of the columns in the df
cols.pop(cols.index('koi_pdisposition')) #Remove 'koi_pdisposition' from list
exoplanets_df = exoplanets_df[cols+['koi_pdisposition']] #Create new dataframe with columns in the order I want
exoplanets_df.head()

kepid kepoi_name   kepler_name koi_disposition  koi_score  koi_period  \
0  10797460  K00752.01  Kepler-227 b       CONFIRMED      1.000    9.488036   
1  10797460  K00752.02  Kepler-227 c       CONFIRMED      0.969   54.418383   
2  10811496  K00753.01           NaN  FALSE POSITIVE      0.000   19.899140   
3  10848459  K00754.01           NaN  FALSE POSITIVE      0.000    1.736952   
4  10854555  K00755.01  Kepler-664 b       CONFIRMED      1.000    2.525592   

   koi_depth  koi_srad  koi_steff  is_train koi_pdisposition  
0      615.8     0.927     5455.0     False        CANDIDATE  
1      874.8     0.927     5455.0      True        CANDIDATE  
2    10829.0     0.868     5853.0      True   FALSE POSITIVE  
3     8079.2     0.791     5805.0      True   FALSE POSITIVE  
4      603.3     1.046     6031.0      True        CANDIDATE

In [20]:
# Create two new dataframes to train and test the model using the created column
train, test = exoplanets_df[exoplanets_df["is_train"]==True], exoplanets_df[exoplanets_df["is_train"]==False]

In [21]:
# see the shape of both dataframes
print(f"Shape of train data: {train.shape}")
print(f"Shape of test data: {test.shape}")

Shape of train data: (5984, 11)
Shape of test data: (2011, 11)


### Preprocess data

In [82]:
# Create a list of the feature column's names
features = exoplanets_df.columns[5:9]
features

Index(['koi_period', 'koi_depth', 'koi_srad', 'koi_steff'], dtype='object')

In [83]:
exoplanets_df["koi_disposition"].unique()

array(['CONFIRMED', 'FALSE POSITIVE', 'CANDIDATE'], dtype=object)

In [84]:
# create just one column with the CANDIDATE, FALSE POSITIVE or CONFIRMED as Numbers
y = pd.factorize(train["koi_disposition"])[0]
y

array([0, 1, 1, ..., 1, 2, 1], dtype=int64)

In [85]:
unique_list = []
for x in y:
    if x not in unique_list:
        unique_list.append(x)

for x in unique_list:
    print(x)

0
1
2


## Train the Random Forest Classifier

In [86]:
# Create the classifier
clf = RandomForestClassifier(n_estimators=200)
# train it with thte columns that we want (features) and the results for that features (y) 
clf.fit(train[features],y)

RandomForestClassifier(n_estimators=200)

## Apply the classifier to the test data

In [87]:
clf.predict(test[features])

array([0, 1, 0, ..., 2, 2, 1], dtype=int64)

In [88]:
# view the predicted probabilities of the first 25 observations
clf.predict_proba(test[features])[0:25]

array([[0.575, 0.045, 0.38 ],
       [0.265, 0.675, 0.06 ],
       [0.445, 0.39 , 0.165],
       [0.   , 0.93 , 0.07 ],
       [0.62 , 0.22 , 0.16 ],
       [0.175, 0.68 , 0.145],
       [0.3  , 0.365, 0.335],
       [0.54 , 0.31 , 0.15 ],
       [0.135, 0.74 , 0.125],
       [0.825, 0.11 , 0.065],
       [0.035, 0.92 , 0.045],
       [0.22 , 0.725, 0.055],
       [0.09 , 0.865, 0.045],
       [0.45 , 0.48 , 0.07 ],
       [0.14 , 0.83 , 0.03 ],
       [0.13 , 0.785, 0.085],
       [0.745, 0.155, 0.1  ],
       [0.265, 0.225, 0.51 ],
       [0.685, 0.04 , 0.275],
       [0.185, 0.735, 0.08 ],
       [0.355, 0.275, 0.37 ],
       [0.195, 0.795, 0.01 ],
       [0.555, 0.25 , 0.195],
       [0.355, 0.52 , 0.125],
       [0.405, 0.575, 0.02 ]])

In [89]:
clf.predict(test[features])

array([0, 1, 0, ..., 2, 2, 1], dtype=int64)

In [90]:
clf.score(test[features].values, clf.predict(test[features]))

1.0

In [91]:
preds = test.copy()
preds["predicted"] = clf.predict(test[features])
preds = preds.loc[preds.index.intersection(clf.predict(test[features]))]

In [92]:
preds["koi_disposition"].unique()

array(['CONFIRMED'], dtype=object)

In [93]:
preds

kepid kepoi_name   kepler_name koi_disposition  koi_score  koi_period  \
0   10797460  K00752.01  Kepler-227 b       CONFIRMED        1.0    9.488036   
0   10797460  K00752.01  Kepler-227 b       CONFIRMED        1.0    9.488036   
0   10797460  K00752.01  Kepler-227 b       CONFIRMED        1.0    9.488036   
0   10797460  K00752.01  Kepler-227 b       CONFIRMED        1.0    9.488036   
0   10797460  K00752.01  Kepler-227 b       CONFIRMED        1.0    9.488036   
..       ...        ...           ...             ...        ...         ...   
0   10797460  K00752.01  Kepler-227 b       CONFIRMED        1.0    9.488036   
0   10797460  K00752.01  Kepler-227 b       CONFIRMED        1.0    9.488036   
0   10797460  K00752.01  Kepler-227 b       CONFIRMED        1.0    9.488036   
0   10797460  K00752.01  Kepler-227 b       CONFIRMED        1.0    9.488036   
0   10797460  K00752.01  Kepler-227 b       CONFIRMED        1.0    9.488036   

    koi_depth  koi_srad  koi_steff  is_train koi_pdisposition  predicted  
0       615.8     0.927     5455.0     False        CANDIDATE          0  
0       615.8     0.927     5455.0     False        CANDIDATE          0  
0       615.8     0.927     5455.0     False        CANDIDATE          0  
0       615.8     0.927     5455.0     False        CANDIDATE          0  
0       615.8     0.927     5455.0     False        CANDIDATE          0  
..        ...       ...        ...       ...              ...        ...  
0       615.8     0.927     5455.0     False        CANDIDATE          0  
0       615.8     0.927     5455.0     False        CANDIDATE          0  
0       615.8     0.927     5455.0     False        CANDIDATE          0  
0       615.8     0.927     5455.0     False        CANDIDATE          0  
0       615.8     0.927     5455.0     False        CANDIDATE          0  

[622 rows x 12 columns]

In [94]:
preds["predicted"].unique()

array([0], dtype=int64)

In [95]:
#pd.crosstab(test["koi_disposition"],preds, rownames=["Actual"], colnames=["Predicted"] )

In [97]:
sorted(zip(train[features], clf.feature_importances_))

[('koi_depth', 0.31486729342021613),
 ('koi_period', 0.2861761313660855),
 ('koi_srad', 0.20219979540036148),
 ('koi_steff', 0.1967567798133368)]